### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by momszx** [CoderSau/react-flexy-table#11]
When i add additionalCols and i click the next button the additions colums values don't change . But the tabele other elements change . And the demo additionalCols not work . they give back undefined

**Comment by CoderSau** [comment]
Hi momszx,

The point of additional columns is to be same for every element on the table. You can use additional columns for adding action buttons for your data like editing,deleting etc. 

https://react-flexy-table.netlify.app/

in the demo above here I use additional columns for listing 2 button (edit,deleting). And I give that a simple alert function.

(undefined is not important here this is just a value but I will fix it )

If you want to add a different additional column value for each row in the table this library does not support that. 
Instead of doing that you can combine this 2 different data in one array and you can use that array in table. 

If you have any other question please let me know.

**Comment by momszx** [comment]
Sorry i think i write my problem bad . 
I have a tabel like this .
|         Id       |Name                          |email |action                        |
|----------------|-------------------------------|-----------------------------|---|
|1|1NAME            |1email@email.com            |modify button
|2        |2NAME             |2email@email.com               |modify button
|3        |3NAME |3email@email.com   |modify button
|4|4NAME           |4email@email.com               |modify button
|5|5NAME             |5email@email.com               |modify button

whit lot off rows . In the firth N rows modify buttons what is rendered by your table its whork fine . When i click the 1th modify button my modify element get the 1th row datast (like id:1 name: 1NAME, email:1email@email.com . 
BUT 
when i hit the next button and the tabele changel to this
|6|6NAME            |6email@email.com            |modify button(click)
|7        |7NAME             |7email@email.com               |modify button
|8        |8NAME |8email@email.com   |modify button
|9|9NAME           |9email@email.com               |modify button
|10|10NAME             |10email@email.com               |modify button
When i click the 6 row modify button my modify element get the 1row elements (id:1 name: 1NAME, email:1email@email.com)
same problem when i use Search

**Comment by CoderSau** [comment]
Hi momszx,

Thank you for this feedback. I updated the version. Can you please check again on your machine and the demo

version 1.7.1

https://react-flexy-table.netlify.app/
