### ISSUE TITLE
Delete row does not function in the demo

### ISSUE THREAD

**Issue by RuiRitaYang** [CoderSau/react-flexy-table#8]
Dear contributors,

I was playing with the demo that you provided in the README.md (which I assume is the code in example folder).  However, it seems like the deletion and Edit function is just an icon with a notification, but they could not actually work. Did I use it in a wrong way?

Thanks,
-Rui

**Comment by CoderSau** [comment]
Yes it didnt works. Because I was just wanna show how to add additional columns in table. My purpuse is not delete rows. I wanted to show how to add edit-delete button (or anything you want) in a additional column.

İf you want to delete you need to change data props you pass in table. For do that you can add a column and return a delete button. In the button is onclick function you can delete data with the column id (or anything you want). When the props change table will updated too. 

Thanks for the idea. Maybe I can add a feature about deleting data in table.
